export const regionOfExpertiseValues = [
  { value: '', name: 'Region of Expertise'},
  { value: 'Afghanistan', name: 'Afghanistan'},
  { value: 'Africa', name: 'Africa'},
  { value: 'Asia-Pacific region', name: 'Asia-Pacific region'},
  { value: 'Asia', name: 'Asia'},
  { value: 'Benin', name: 'Benin'},
  { value: 'Burundi', name: 'Burundi'},
  { value: 'Cambodia', name: 'Cambodia'},
  { value: 'Colombia', name: 'Colombia'},
  { value: 'Cote d’Ivoire', name: 'Cote d’Ivoire'},
  { value: 'Croatia', name: 'Croatia'},
  { value: 'Egypt', name: 'Egypt'},
  { value: 'El Salvador', name: 'El Salvador'},
  { value: 'Ethiopia', name: 'Ethiopia'},
  { value: 'EU', name: 'EU'},
  { value: 'Ghana', name: 'Ghana'},
  { value: 'Haiti', name: 'Haiti'},
  { value: 'India', name: 'India'},
  { value: 'Indonesia', name: 'Indonesia'},
  { value: 'Israel/Palestine', name: 'Israel/Palestine'},
  { value: 'Jamaica', name: 'Jamaica'},
  { value: 'Kenya', name: 'Kenya'},
  { value: 'Kosovo', name: 'Kosovo'},
  { value: 'Liberia', name: 'Liberia'},
  { value: 'Mali', name: 'Mali'},
  { value: 'Middle East', name: 'Middle East'},
  { value: 'Nepal', name: 'Nepal'},
  { value: 'Pakistan', name: 'Pakistan'},
  { value: 'Peru', name: 'Peru'},
  { value: 'Philippines', name: 'Philippines'},
  { value: 'Latin America', name: 'Latin America'},
  { value: 'Mozambique', name: 'Mozambique'},
  { value: 'Myanmar', name: 'Myanmar'},
  { value: 'Niger', name: 'Niger'},
  { value: 'Republic of Congo', name: 'Republic of Congo'},
  { value: 'Rwanda', name: 'Rwanda'},
  { value: 'Senegal', name: 'Senegal'},
  { value: 'Sierra Leone', name: 'Sierra Leone'},
  { value: 'South Africa', name: 'South Africa'},
  { value: 'Southeast Asia', name: 'Southeast Asia'},
  { value: 'Sri Lanka', name: 'Sri Lanka'},
  { value: 'Sub-Saharan Africa', name: 'Sub-Saharan Africa'},
  { value: 'Tanzania', name: 'Tanzania'},
  { value: 'Thailand', name: 'Thailand'},
  { value: 'Timor', name: 'Timor'},
  { value: 'Turkey', name: 'Turkey'},
  { value: 'Yemen', name: 'Yemen'}
  
];