//Constants
/* export const FETCH_RESEARCHER = 'FETCH_RESEARCHER';
export const FETCH_ALL_RESEARCHERS = 'FETCH_ALL_RESEARCHERS'; */

export const RESEARCHER_ITEMS_HAS_ERRORED = 'RESEARCHER_ITEMS_HAS_ERRORED';
export const RESEARCHER_ITEMS_IS_LOADING = 'RESEARCHER_ITEMS_IS_LOADING';
export const RESEARCHER_ITEMS_FETCH_DATA_SUCCESS = 'RESEARCHER_ITEMS_FETCH_DATA_SUCCESS';

export const RESEARCHER_ITEMS_ARE_EMPTY = 'RESEARCHER_ITEMS_ARE_EMPTY';

export const TOGGLE_DISPLAY = 'TOGGLE_DISPLAY';
export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';



