//Constants

export const RESEARCHER_ITEMS_HAS_ERRORED = 'RESEARCHER_ITEMS_HAS_ERRORED';
export const RESEARCHER_ITEMS_IS_LOADING = 'RESEARCHER_ITEMS_IS_LOADING';
export const RESEARCHER_ITEMS_FETCH_DATA_SUCCESS = 'RESEARCHER_ITEMS_FETCH_DATA_SUCCESS';

export const RESEARCHER_ITEMS_ARE_EMPTY = 'RESEARCHER_ITEMS_ARE_EMPTY';
export const FILTER_ITEMS_ARE_EMPTY = 'FILTER_ITEMS_ARE_EMPTY';

export const TOGGLE_DISPLAY = 'TOGGLE_DISPLAY';
export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';

export const RESEARCHER_ITEMS_FILTER_BY_GROUP = 'RESEARCHER_ITEMS_FILTER_BY_GROUP';
export const RESEARCHER_ITEMS_FILTER_BY_REGION = 'RESEARCHER_ITEMS_FILTER_BY_REGION';
export const RESEARCHER_ITEMS_FILTER_BY_FIELD = 'RESEARCHER_ITEMS_FILTER_BY_FIELD';
export const RESEARCHER_ITEMS_ARE_FILTERED = 'RESEARCHER_ITEMS_IS_FILTERED';
export const FETCH_NAMES = 'FETCH_NAMES ';


